INSERT INTO Assets (asset_id, token, network, account_based)
VALUES
	('ADA_TEST', 'ADA', 'ADA', 0),
	('BTC_TEST', 'BTC', 'BTC', 0),
	('ALGO_TEST', 'ALGO', 'ALGO', 0),
	('AVAXTEST', 'AVAX', 'AVAXC', 1),
-- 	('', 'ATOM', 'COSMOS', 1),
-- 	('', 'DOT', 'DOT', 1),
--	('', 'FTM', 'FANTOM', 1),
	('MATIC_POLYGON_MUMBAI', 'MATIC', 'POLYGON', 1),
	('SOL_TEST', 'SOL', 'SOL', 1),
--	('', 'USDT', 'TRC20', 1),
	('LUNA_TEST', 'LUNA', 'TERRA', 0),
	('TERRA_USD_TEST', 'UST', 'TERRA', 0),
	('UNI_TEST', 'UNI', 'ERC20', 1),
	('MATIC_TEST', 'MATIC', 'ERC20', 1),
	('SAND_TEST', 'SAND', 'ERC20', 1),
--	('', 'MANA', 'ERC20', 1),
--	('', 'SLP', 'ERC20', 1),
	('ETH_TEST', 'ETH', 'ERC20', 1),
	('USDT_TEST', 'USDT', 'ERC20', 1),
	('USDC_ETH_TEST2', 'USDC', 'ERC20', 1),
	('AXS_TEST', 'AXS', 'ERC20', 1),
	('DAI_T', 'DAI', 'ERC20', 1),
	('MATIC_TEST', 'MATIC', 'BEP20', 1),
--	('', 'CAKE', 'BEP20', 1),
--	('', 'DOT', 'BEP20', 1),
	('USDT_BSC_TEST', 'USDT', 'BEP20', 1),
	('DAI_T', 'DAI', 'BEP20', 1),
--	('', 'ATOM', 'BEP20', 1),
--	('', 'BTC', 'BEP20', 1),
	('DAI_UNI_TEST', 'UNI', 'BEP20', 1),
--	('', 'SOL', 'BEP20', 1),
--	('', 'AVAX', 'BEP20', 1),
--	('', 'SLP', 'BEP20', 1),
--	('', 'UST', 'BEP20', 1),
	('BNB_TEST', 'BNB', 'BEP20', 1),
--	('', 'ETH', 'BEP20', 1),
--	('', 'AXS', 'BEP20', 1),
--	('', 'ADA', 'BEP20', 1),
--	('', 'FTM', 'BEP20', 1),
	('USDC_TEST', 'USDC', 'BEP20', 1);
